import adminModel from '../models/admin.model'
import customerModel from '../models/customer.model'
import gpPartnerModel from '../models/gp.partner.model'
import labModel from '../models/lab.model'
import serviceProviderModel from '../models/service.provider.model'
import { FRONTEND_URL } from '../plugins/env'
import '../database'

export enum APPROVAL_STATUS {
  APPROVED = 'APPROVED',
  PENDING = 'PENDING',
  DECLINED = 'DECLINED',
}

export enum PAYMENT_STATUS {
  PAID = 'PAID',
  PENDING = 'PENDING',
  NOT_PAID = 'NOT_PAID',
}

export enum SERVER {
  LOCAL = 'local',
  DEV = 'development',
  STAGING = 'staging',
  PROD = 'production',
}
export enum HOST {
  LOCAL = 'localhost:9000',
  DEV = 'dev.mobilab2u.com',
  PROD = 'mobilab2u.com',
  STAGING = 'stage.mobilab2u.com',
}

export enum CUSTOMER_LAB_TEST_STATUS {
  SERVICE_PROVIDER_APPROVED = 'SERVICE_PROVIDER_APPROVED',
  DECLINED = 'DECLINED',
  SAMPLE_COLLECTED = 'SAMPLE_COLLECTED',
  SAMPLE_RE_COLLECTED = 'SAMPLE_RE_COLLECTED',
  SAMPLE_SUBMITTED_TO_LAB = 'SAMPLE_SUBMITTED_TO_LAB',
  RE_COLLECTED_SAMPLE_SUBMITTED_TO_LAB = 'RE_COLLECTED_SAMPLE_SUBMITTED_TO_LAB',
  NEED_SAMPLE_RE_COLLECTION = 'NEED_SAMPLE_RE_COLLECTION',
  LAB_ASSIGNED = 'LAB_ASSIGNED',
  TEST_COMPLETED = 'TEST_COMPLETED',
  PROCESSING = 'PROCESSING',
  CANCELLED = 'CANCELLED',
  SAMPLE_RE_COLLECTION_APPROVED = 'SAMPLE_RE_COLLECTION_APPROVED',
}

export const CUSTOMER_TEST_VALID_TRANSACTIONS: Record<string, Array<string>> = {
  [CUSTOMER_LAB_TEST_STATUS.PROCESSING]: [
    CUSTOMER_LAB_TEST_STATUS.SERVICE_PROVIDER_APPROVED,
    CUSTOMER_LAB_TEST_STATUS.DECLINED,
  ],
  [CUSTOMER_LAB_TEST_STATUS.SERVICE_PROVIDER_APPROVED]: [
    CUSTOMER_LAB_TEST_STATUS.LAB_ASSIGNED,
  ],
  [CUSTOMER_LAB_TEST_STATUS.LAB_ASSIGNED]: [
    CUSTOMER_LAB_TEST_STATUS.SAMPLE_COLLECTED,
  ],
  [CUSTOMER_LAB_TEST_STATUS.SAMPLE_COLLECTED]: [
    CUSTOMER_LAB_TEST_STATUS.SAMPLE_SUBMITTED_TO_LAB,
  ],
  [CUSTOMER_LAB_TEST_STATUS.SAMPLE_SUBMITTED_TO_LAB]: [
    CUSTOMER_LAB_TEST_STATUS.TEST_COMPLETED,
    CUSTOMER_LAB_TEST_STATUS.NEED_SAMPLE_RE_COLLECTION,
  ],
  [CUSTOMER_LAB_TEST_STATUS.NEED_SAMPLE_RE_COLLECTION]: [
    CUSTOMER_LAB_TEST_STATUS.SAMPLE_RE_COLLECTION_APPROVED,
  ],
  [CUSTOMER_LAB_TEST_STATUS.SAMPLE_RE_COLLECTION_APPROVED]: [
    CUSTOMER_LAB_TEST_STATUS.SAMPLE_RE_COLLECTED,
  ],
  [CUSTOMER_LAB_TEST_STATUS.SAMPLE_RE_COLLECTED]: [
    CUSTOMER_LAB_TEST_STATUS.RE_COLLECTED_SAMPLE_SUBMITTED_TO_LAB,
  ],
  [CUSTOMER_LAB_TEST_STATUS.RE_COLLECTED_SAMPLE_SUBMITTED_TO_LAB]: [
    CUSTOMER_LAB_TEST_STATUS.TEST_COMPLETED,
    CUSTOMER_LAB_TEST_STATUS.NEED_SAMPLE_RE_COLLECTION,
  ],
  [CUSTOMER_LAB_TEST_STATUS.TEST_COMPLETED]: [],
  [CUSTOMER_LAB_TEST_STATUS.CANCELLED]: [],
}

export const HSP_VALID_TRANSACTIONS = [
  CUSTOMER_LAB_TEST_STATUS.SERVICE_PROVIDER_APPROVED,
  CUSTOMER_LAB_TEST_STATUS.LAB_ASSIGNED,
  CUSTOMER_LAB_TEST_STATUS.SAMPLE_COLLECTED,
  CUSTOMER_LAB_TEST_STATUS.SAMPLE_SUBMITTED_TO_LAB,
  CUSTOMER_LAB_TEST_STATUS.RE_COLLECTED_SAMPLE_SUBMITTED_TO_LAB,
  CUSTOMER_LAB_TEST_STATUS.SAMPLE_RE_COLLECTED,
  CUSTOMER_LAB_TEST_STATUS.DECLINED,
]

export const PURCHASED_MEDICINE_STATUS = {
  PURCHASED: 'PURCHASED',
}

export const REFRESH_TOKEN = 'refreshToken'

export const ROUTES = {
  PAYMENT_SUCCESS: `${FRONTEND_URL}/payment/success`,
  PAYMENT_FAILURE: `${FRONTEND_URL}/payment/failure`,
}

export enum COUNTER_TYPE {
  CUSTOMER_REGISTRATION_NUMBER = 'CUSTOMER_REGISTRATION_NUMBER',
}

export enum COUNTRY {
  MALAYSIA = 'MALAYSIA',
}

export const CUSTOMER_LAB_TEST_STATUS_OPTIONS: Record<string, string> = {
  SERVICE_PROVIDER_APPROVED: 'Approved',
  DECLINED: 'Declined',
  SAMPLE_COLLECTED: 'sample collected',
  LAB_ASSIGNED: 'lab assigned',
  SAMPLE_SUBMITTED_TO_LAB: 'sample submitted to lab',
  NEED_SAMPLE_RE_COLLECTION: 'sample re-collection updated',
  SAMPLE_RE_COLLECTED: 'sample re-collected',
  RE_COLLECTED_SAMPLE_SUBMITTED_TO_LAB: 're-collected sample submitted to lab',
}

export const API_METHODS = ['POST', 'PUT', 'GET', 'PATCH', 'DELETE']
export const models: Record<string, any> = {
  SERVICE_PROVIDER: serviceProviderModel,
  GP_PARTNER: gpPartnerModel,
  LAB_USER: labModel,
  CUSTOMER: customerModel,
  SUPER_ADMIN: adminModel,
}

export const ROLES_TO_STRING: Record<string, string> = {
  SERVICE_PROVIDER: 'Health Service Provider',
  GP_PARTNER: 'G.P Partner',
  LAB_USER: 'Lab User',
  CUSTOMER: 'Customer',
}
export enum PAYMENT_TYPE {
  TEST_FEES = 'TEST_FEES',
  FOLLOWUP_TEST_FEES = 'FOLLOWUP_TEST_FEES',
  APPOINTMENT_FEES = 'APPOINTMENT_FEES',
  RANDOM_DOCTOR_FOLLOWUP_APPOINTMENT_FEES = 'RANDOM_DOCTOR_FOLLOWUP_APPOINTMENT_FEES',
  FOLLOWUP_DOCTOR_FOLLOWUP_APPOINTMENT_FEES = 'FOLLOWUP_DOCTOR_FOLLOWUP_APPOINTMENT_FEES',
  SERVICE_PROVIDER_KIT_FEES = 'SERVICE_PROVIDER_KIT_FEES',
  MEDICINE_FEES = 'MEDICINE_FEES',
}

export enum CUSTOMER_CONSULTATION_STATUS {
  APPROVED = 'APPROVED',
  DOCTOR_CONSULTATION_DONE = 'DOCTOR_CONSULTATION_DONE',
  COMPLETED = 'COMPLETED',
  PENDING = 'PENDING',
  ADMIN_APPROVED = 'ADMIN_APPROVED',
  CANCELLED = 'CANCELLED',
  DOCTOR_CONFIRMED = 'DOCTOR_CONFIRMED',
}

export enum APPOINTMENT_TYPE {
  NORMAL_APPOINTMENT = 'NORMAL_APPOINTMENT',
  RANDOM_DOCTOR_FOLLOWUP_APPOINTMENT = 'RANDOM_DOCTOR_FOLLOWUP_APPOINTMENT',
  FOLLOWUP_DOCTOR_FOLLOWUP_APPOINTMENT = 'FOLLOWUP_DOCTOR_FOLLOWUP_APPOINTMENT',
}
export enum OTP_AUTH_OPTIONS {
  REGISTER = 'REGISTER',
  WALLET_REDEEM = 'WALLET_REDEEM',
  UPDATE = 'UPDATE',
  CUSTOMER_OTP_FROM_HSP = 'CUSTOMER_OTP_FROM_HSP',
  LAB_OTP_FROM_HSP = 'LAB_OTP_FROM_HSP',
}

export enum PACKAGE_TYPE {
  TEST = 'TEST',
  APPOINTMENT = 'APPOINTMENT',
  SERVICE_PROVIDER_KIT_FEES = 'SERVICE_PROVIDER_KIT_FEES',
  FOLLOWUP_APPOINTMENT = 'FOLLOWUP_APPOINTMENT',
  APPOINTMENT_CANCELLATION = 'APPOINTMENT_CANCELLATION',
  TEST_CANCELLATION = 'TEST_CANCELLATION',
  WALLET_REDEEM_REQUEST = 'WALLET_REDEEM_REQUEST',
  WALLET_REDEEM_REQUEST_DECLINE = 'WALLET_REDEEM_REQUEST_DECLINE',
}

export enum QUEUE_OPTIONS {
  EMAIL = 'EMAIL',
  WHATSAPP = 'WHATSAPP',
}

export enum QUEUE_TYPE {
  REMAINDER_QUEUE = 'remainder-queue',
}

export enum HSP_STATUS {
  ACTIVE = 'ACTIVE',
  DE_ACTIVE = 'DE_ACTIVE',
}

export enum PACKAGE_OPTION {
  FAMILY = 'FAMILY',
  INDIVIDUAL = 'INDIVIDUAL',
}

export const NEW = 'NEW'

export const CREATE_CUSTOM_PACKAGE = 'CREATE_CUSTOM_PACKAGE'

export const date = new Date()

export const year = date.getUTCFullYear()
export const month = date.getUTCMonth() + 1
export const day = date.getUTCDate()
