name: 🐞 Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["Bug"]
projects: ["Santheepkumar/6"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: describe-bug
    attributes:
      label: Describe the bug
      description: Tell us, what happened?
      placeholder: What you see!
      value: "A bug happened!"
    validations:
      required: true

  - type: textarea
    id: expected-behaviour
    attributes:
      label: What is expected?
      description: Tell us, what did you expect to happen?
      placeholder: Tell us what is expected!
      value: "Expected something!"
    validations:
      required: false
      
  - type: textarea
    id: how-to-reproduce
    attributes:
      label: How to Reproduce?
      description: Also tell us, How to reproduce the bug?
      placeholder: Tell us How to reproduce
      value: "Steps to reproduce"
    validations:
      required: false
  - type: textarea
    id: attachments
    attributes:
      label: Any Screenshots or Videos?
      description: Add some Screenshots or videos?
      placeholder: Drag and drop or attach files
    validations:
      required: false

  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell