/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface AdminUpdateGPProfileSchema {
  name: string;
  phone: number;
  city: string;
  state: string;
  address: string;
  postCode: string;
  userId: string;
  userRole: string;
  [k: string]: unknown;
}
