/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CreateCustomPackageSchema = CreateCustomPackageSchema1 & CreateCustomPackageSchema2;
export type CreateCustomPackageSchema1 = {
  [k: string]: unknown;
};

export interface CreateCustomPackageSchema2 {
  packageName: string;
  packageDescription: string;
  selectedPackage: string;
  name?: string;
  description?: string;
  type?: string;
  members?: number;
  serviceType?: string;
  price?: number;
  labShare?: number;
  gpShare?: number;
  hspShare?: number;
  duration?: string;
  fastingHour?: string;
  customerShare?: number;
  mobilabShare?: number;
  offerPrice?: number;
  document?: {
    [k: string]: unknown;
  };
  image?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
