/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CreateCustomerTestSchema {
  customerAppointmentDate: string;
  customerAppointmentTime: string;
  members?: {
    name?: string;
    age?: string;
    gender?: string;
    [k: string]: unknown;
  }[];
  customerAddress: {
    city: string;
    state: string;
    address: string;
    postCode: string;
    [k: string]: unknown;
  };
  referredDoctor?: string;
  packageId: string;
  addressType?: "OLD" | "NEW";
  [k: string]: unknown;
}
