/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CustomerUpdateProfileSchema = CustomerUpdateProfileSchema1 & CustomerUpdateProfileSchema2;
export type CustomerUpdateProfileSchema1 = {
  [k: string]: unknown;
};

export interface CustomerUpdateProfileSchema2 {
  name: string;
  gender?: string;
  passportSizePhoto?: {
    [k: string]: unknown;
  };
  idProof?: string;
  phone: number;
  dateOfBirth: string;
  otp?: string;
  primaryAddress: {
    city: string;
    state: string;
    address: string;
    postCode: string;
    lat?: number;
    lng?: number;
    [k: string]: unknown;
  };
  secondaryAddress?: {
    city?: string;
    state?: string;
    address?: string;
    postCode?: string;
    lat?: number;
    lng?: number;
    [k: string]: unknown;
  }[];
  nricNumber?: string;
  passportNumber?: string;
  [k: string]: unknown;
}
