/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CustomerRegisterSchema = CustomerRegisterSchema1 & CustomerRegisterSchema2;
export type CustomerRegisterSchema1 = {
  [k: string]: unknown;
};

export interface CustomerRegisterSchema2 {
  name: string;
  gender: string;
  phone: number;
  email: string;
  nricNumber?: string;
  passportNumber?: string;
  idProof: "PASSPORT_NUMBER" | "NRIC_NUMBER";
  postCode: string;
  lat?: number;
  lng?: number;
  address: string;
  state: string;
  city: string;
  password: string;
  emailCode: string;
  otp: boolean;
  dateOfBirth: string;
  [k: string]: unknown;
}
