/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ENVSchema {
  PORT: string;
  NODE_ENV: string;
  SERVER_HOSTNAME: string;
  MONGO_CONNECTION_STRING: string;
  JWT_SECRET: string;
  COOKIE_SECRET: string;
  ACCESS_EXPIRE: string;
  REFRESH_EXPIRE: string;
  ALLOWED_ORIGINS: string;
  REDIS_DB: string;
  AWS_ACCESS_KEY_ID: string;
  AWS_SECRET_ACCESS_KEY: string;
  S3_BUCKET_NAME: string;
  UPLOAD_TO_S3: string;
  AWS_REGION: string;
  SMTP_SECRET_PASSWORD: string;
  SMTP_PORT: string;
  SMTP_SECRET_USER: string;
  SMTP_HOST: string;
  SMTP_SENDER: string;
  SENTRY_DSN: string;
  STRIPE_PUBLISHABLE_KEY: string;
  STRIPE_SECRET_KEY: string;
  STRIPE_WEBHOOK_SECRET_KEY: string;
  FRONTEND_URL: string;
  ZOOM_ACCOUNT_ID: string;
  ZOOM_CLIENT_ID: string;
  ZOOM_CLIENT_SECRET: string;
  ZOOM_SECRET_TOKEN: string;
  ZOOM_VERIFICATION_TOKEN: string;
  TWILIO_ACCOUNT_SID: string;
  TWILIO_AUTH_TOKEN: string;
  TWILIO_PHONE_NUMBER: string;
  TWILIO_WHATSAPP_NUMBER: string;
  [k: string]: unknown;
}
