/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface LabTestReportBodySchema {
  reportDocOne: {
    [k: string]: unknown;
  };
  reportDocTwo?: {
    [k: string]: unknown;
  };
  reportDocThree?: {
    [k: string]: unknown;
  };
  reportDocFour?: {
    [k: string]: unknown;
  };
  reportDocFive?: {
    [k: string]: unknown;
  };
  reportDocSix?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
