/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface LabBodySchema {
  name: string;
  email: string;
  phone: string;
  organization: string;
  postCode: string;
  city: string;
  state: string;
  address: string;
  password: string;
  [k: string]: unknown;
}
