/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type PackageBodySchema = PackageBodySchema1 & PackageBodySchema2;
export type PackageBodySchema1 = {
  [k: string]: unknown;
};

export interface PackageBodySchema2 {
  labShare: number;
  hspShare: number;
  customerShare: number;
  mobilabShare: number;
  description: string;
  type: "FAMILY" | "INDIVIDUAL";
  members?: number;
  serviceType: "SERVICE_PROVIDER_KIT_FEES" | "TEST" | "APPOINTMENT";
  price: number;
  offerPrice?: number;
  document: {
    [k: string]: unknown;
  };
  image: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
