/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface RegisterSchema {
  roles: "SERVICE_PROVIDER" | "GP_PARTNER";
  userName: string;
  gender: string;
  phone: number;
  email: string;
  medicalQualification: "DOCTOR" | "PARADEMIC" | "NURSES" | "OTHERS";
  other?: string;
  nricNumber: string;
  postCode: string;
  address: string;
  address2?: string;
  state: string;
  city: string;
  password: string;
  emailCode: string;
  mQdocOne: {
    [k: string]: unknown;
  };
  mQdocTwo: {
    [k: string]: unknown;
  };
  mQdocThree?:
    | {
        [k: string]: unknown;
      }
    | string;
  mQdocFour?:
    | {
        [k: string]: unknown;
      }
    | string;
  passportSizePhoto: {
    [k: string]: unknown;
  };
  myKad: {
    [k: string]: unknown;
  };
  supportingDocs?: unknown[];
  [k: string]: unknown;
}

export interface Docs {
  mQdocFour: { _id: string };
  mQdocThree: { _id: string };
  eSign: { _id: string };
}
