/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ReviewCustomerTestBodySchema = ReviewCustomerTestBodySchema1 & ReviewCustomerTestBodySchema2;
export type ReviewCustomerTestBodySchema1 = {
  [k: string]: unknown;
};

export interface ReviewCustomerTestBodySchema2 {
  status:
    | "SERVICE_PROVIDER_APPROVED"
    | "DECLINED"
    | "PENDING"
    | "SAMPLE_COLLECTED"
    | "SAMPLE_SUBMITTED_TO_LAB"
    | "LAB_ASSIGNED"
    | "NEED_SAMPLE_RE_COLLECTION"
    | "SAMPLE_RE_COLLECTED"
    | "RE_COLLECTED_SAMPLE_SUBMITTED_TO_LAB";
  declineNote?: string;
  testId: string;
  reason?: string;
  labId?: string;
  [k: string]: unknown;
}
