/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type SPRegisterSchema = SPRegisterSchema1 & SPRegisterSchema2;
export type SPRegisterSchema1 = {
  [k: string]: unknown;
};

export interface SPRegisterSchema2 {
  roles: "SERVICE_PROVIDER" | "GP_PARTNER";
  userName: string;
  lat?: number;
  lng?: number;
  idProof: "PASSPORT_NUMBER" | "NRIC_NUMBER";
  eSign?:
    | {
        [k: string]: unknown;
      }
    | string;
  gender: string;
  language?: string;
  registerNumber: string;
  phone: number;
  email: string;
  medicalQualification: "DOCTOR" | "PARADEMIC" | "NURSES" | "OTHERS";
  other?: string;
  nricNumber?: string;
  passportNumber?: string;
  postCode: string;
  address: string;
  address2?: string;
  state: string;
  city: string;
  password: string;
  emailCode: string;
  mQdocOne: {
    [k: string]: unknown;
  };
  mQdocTwo: {
    [k: string]: unknown;
  };
  mQdocThree?:
    | {
        [k: string]: unknown;
      }
    | string;
  mQdocFour?:
    | {
        [k: string]: unknown;
      }
    | string;
  passportSizePhoto: {
    [k: string]: unknown;
  };
  myKad: {
    [k: string]: unknown;
  };
  supportingDocs?: unknown[];
  [k: string]: unknown;
}
