/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type UpdateUserProfileSchema = UpdateUserProfileSchema1 & UpdateUserProfileSchema2;
export type UpdateUserProfileSchema1 = {
  [k: string]: unknown;
};

export interface UpdateUserProfileSchema2 {
  name: string;
  phone: number;
  otp?: string;
  city: string;
  lat?: number;
  lng?: number;
  state: string;
  address: string;
  postCode: string;
  nricNumber?: string;
  passportNumber?: string;
  idProof: string;
  eSign?:
    | {
        [k: string]: unknown;
      }
    | string;
  isESign?: boolean;
  passportSizePhoto?:
    | {
        [k: string]: unknown;
      }
    | string;
  [k: string]: unknown;
}
