/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface UpdateMedicinePriceSchema {
  medicine: unknown[];
  price: number;
  deliveryCharge?: number;
  medicineId: string;
  [k: string]: unknown;
}
